#flyway:
#  baselineOnMigrate: false
spring:
  datasource:
    #db1
      url: jdbc:mysql://192.168.0.2:13306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: root
#      #db2
      url2: jdbc:mysql://192.168.0.2:13306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
      username2: root
      password2: root
#      db-pool-setting
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 10
      maxActive: 20
      initialSize: 5
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'ZTM' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

#flyway:
#  enabled: false


