server:
  port: 8002

spring:
  application:
    name: nacos-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      statistic:
        max:
          rt: 10000
#      eager: true
      transport:
        dashboard: 127.0.0.1:8080
      datasource: #添加Nacos数据源配置
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: nacos-feign-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
